// elements.js — Full 118 elements with extra data (ready for future upgrades!)
const elements = [
    {atomicNumber:1,symbol:"H",name:"Hydrogen",cpkHexColor:"FFFFFF",groupBlock:"nonmetal"},
    {atomicNumber:2,symbol:"He",name:"Helium",cpkHexColor:"D9FFFF",groupBlock:"noble gas"},
    {atomicNumber:3,symbol:"Li",name:"Lithium",cpkHexColor:"CC80FF",groupBlock:"alkali metal"},
    {atomicNumber:4,symbol:"Be",name:"Beryllium",cpkHexColor:"C2FF00",groupBlock:"alkaline earth metal"},
    {atomicNumber:5,symbol:"B",name:"Boron",cpkHexColor:"FFB5B5",groupBlock:"metalloid"},
    {atomicNumber:6,symbol:"C",name:"Carbon",cpkHexColor:"909090",groupBlock:"nonmetal"},
    {atomicNumber:7,symbol:"N",name:"Nitrogen",cpkHexColor:"3050F8",groupBlock:"nonmetal"},
    {atomicNumber:8,symbol:"O",name:"Oxygen",cpkHexColor:"FF0D0D",groupBlock:"nonmetal"},
    {atomicNumber:9,symbol:"F",name:"Fluorine",cpkHexColor:"90E050",groupBlock:"halogen"},
    {atomicNumber:10,symbol:"Ne",name:"Neon",cpkHexColor:"B3E3F5",groupBlock:"noble gas"},
    {atomicNumber:11,symbol:"Na",name:"Sodium",cpkHexColor:"AB5CF2",groupBlock:"alkali metal"},
    {atomicNumber:12,symbol:"Mg",name:"Magnesium",cpkHexColor:"8AFF00",groupBlock:"alkaline earth metal"},
    {atomicNumber:13,symbol:"Al",name:"Aluminium",cpkHexColor:"BFA6A6",groupBlock:"metal"},
    {atomicNumber:14,symbol:"Si",name:"Silicon",cpkHexColor:"F0C8A0",groupBlock:"metalloid"},
    {atomicNumber:15,symbol:"P",name:"Phosphorus",cpkHexColor:"FF8000",groupBlock:"nonmetal"},
    {atomicNumber:16,symbol:"S",name:"Sulfur",cpkHexColor:"FFFF30",groupBlock:"nonmetal"},
    {atomicNumber:17,symbol:"Cl",name:"Chlorine",cpkHexColor:"1FF01F",groupBlock:"halogen"},
    {atomicNumber:18,symbol:"Ar",name:"Argon",cpkHexColor:"80D1E3",groupBlock:"noble gas"},
    {atomicNumber:19,symbol:"K",name:"Potassium",cpkHexColor:"8F40D4",groupBlock:"alkali metal"},
    {atomicNumber:20,symbol:"Ca",name:"Calcium",cpkHexColor:"3DFF00",groupBlock:"alkaline earth metal"},
    {atomicNumber:21,symbol:"Sc",name:"Scandium",cpkHexColor:"E6E6E6",groupBlock:"transition metal"},
    {atomicNumber:22,symbol:"Ti",name:"Titanium",cpkHexColor:"BFC2C7",groupBlock:"transition metal"},
    {atomicNumber:23,symbol:"V",name:"Vanadium",cpkHexColor:"A6A6AB",groupBlock:"transition metal"},
    {atomicNumber:24,symbol:"Cr",name:"Chromium",cpkHexColor:"8A99C7",groupBlock:"transition metal"},
    {atomicNumber:25,symbol:"Mn",name:"Manganese",cpkHexColor:"9C7AC7",groupBlock:"transition metal"},
    {atomicNumber:26,symbol:"Fe",name:"Iron",cpkHexColor:"E06633",groupBlock:"transition metal"},
    {atomicNumber:27,symbol:"Co",name:"Cobalt",cpkHexColor:"F090A0",groupBlock:"transition metal"},
    {atomicNumber:28,symbol:"Ni",name:"Nickel",cpkHexColor:"50D050",groupBlock:"transition metal"},
    {atomicNumber:29,symbol:"Cu",name:"Copper",cpkHexColor:"C88033",groupBlock:"transition metal"},
    {atomicNumber:30,symbol:"Zn",name:"Zinc",cpkHexColor:"7D80B0",groupBlock:"transition metal"},
    {atomicNumber:31,symbol:"Ga",name:"Gallium",cpkHexColor:"C28F8F",groupBlock:"metal"},
    {atomicNumber:32,symbol:"Ge",name:"Germanium",cpkHexColor:"668F8F",groupBlock:"metalloid"},
    {atomicNumber:33,symbol:"As",name:"Arsenic",cpkHexColor:"BD80E3",groupBlock:"metalloid"},
    {atomicNumber:34,symbol:"Se",name:"Selenium",cpkHexColor:"FFA100",groupBlock:"nonmetal"},
    {atomicNumber:35,symbol:"Br",name:"Bromine",cpkHexColor:"A62929",groupBlock:"halogen"},
    {atomicNumber:36,symbol:"Kr",name:"Krypton",cpkHexColor:"5CB8D1",groupBlock:"noble gas"},
    {atomicNumber:37,symbol:"Rb",name:"Rubidium",cpkHexColor:"702EB0",groupBlock:"alkali metal"},
    {atomicNumber:38,symbol:"Sr",name:"Strontium",cpkHexColor:"00FF00",groupBlock:"alkaline earth metal"},
    {atomicNumber:39,symbol:"Y",name:"Yttrium",cpkHexColor:"94FFFF",groupBlock:"transition metal"},
    {atomicNumber:40,symbol:"Zr",name:"Zirconium",cpkHexColor:"94E0E0",groupBlock:"transition metal"},
    {atomicNumber:41,symbol:"Nb",name:"Niobium",cpkHexColor:"73C2C9",groupBlock:"transition metal"},
    {atomicNumber:42,symbol:"Mo",name:"Molybdenum",cpkHexColor:"54B5B5",groupBlock:"transition metal"},
    {atomicNumber:43,symbol:"Tc",name:"Technetium",cpkHexColor:"3B9E9E",groupBlock:"transition metal"},
    {atomicNumber:44,symbol:"Ru",name:"Ruthenium",cpkHexColor:"248F8F",groupBlock:"transition metal"},
    {atomicNumber:45,symbol:"Rh",name:"Rhodium",cpkHexColor:"0A7D8C",groupBlock:"transition metal"},
    {atomicNumber:46,symbol:"Pd",name:"Palladium",cpkHexColor:"006985",groupBlock:"transition metal"},
    {atomicNumber:47,symbol:"Ag",name:"Silver",cpkHexColor:"C0C0C0",groupBlock:"transition metal"},
    {atomicNumber:48,symbol:"Cd",name:"Cadmium",cpkHexColor:"FFD98F",groupBlock:"transition metal"},
    {atomicNumber:49,symbol:"In",name:"Indium",cpkHexColor:"A67573",groupBlock:"metal"},
    {atomicNumber:50,symbol:"Sn",name:"Tin",cpkHexColor:"668080",groupBlock:"metal"},
    {atomicNumber:51,symbol:"Sb",name:"Antimony",cpkHexColor:"9E63B5",groupBlock:"metalloid"},
    {atomicNumber:52,symbol:"Te",name:"Tellurium",cpkHexColor:"D47A00",groupBlock:"metalloid"},
    {atomicNumber:53,symbol:"I",name:"Iodine",cpkHexColor:"940094",groupBlock:"halogen"},
    {atomicNumber:54,symbol:"Xe",name:"Xenon",cpkHexColor:"429EB0",groupBlock:"noble gas"},
    {atomicNumber:55,symbol:"Cs",name:"Caesium",cpkHexColor:"57178F",groupBlock:"alkali metal"},
    {atomicNumber:56,symbol:"Ba",name:"Barium",cpkHexColor:"00C900",groupBlock:"alkaline earth metal"},
    {atomicNumber:57,symbol:"La",name:"Lanthanum",cpkHexColor:"70D4FF",groupBlock:"lanthanoid"},
    {atomicNumber:58,symbol:"Ce",name:"Cerium",cpkHexColor:"FFFFC7",groupBlock:"lanthanoid"},
    {atomicNumber:59,symbol:"Pr",name:"Praseodymium",cpkHexColor:"D9FFC7",groupBlock:"lanthanoid"},
    {atomicNumber:60,symbol:"Nd",name:"Neodymium",cpkHexColor:"C7FFC7",groupBlock:"lanthanoid"},
    {atomicNumber:61,symbol:"Pm",name:"Promethium",cpkHexColor:"A3FFC7",groupBlock:"lanthanoid"},
    {atomicNumber:62,symbol:"Sm",name:"Samarium",cpkHexColor:"8FFFC7",groupBlock:"lanthanoid"},
    {atomicNumber:63,symbol:"Eu",name:"Europium",cpkHexColor:"61FFC7",groupBlock:"lanthanoid"},
    {atomicNumber:64,symbol:"Gd",name:"Gadolinium",cpkHexColor:"45FFC7",groupBlock:"lanthanoid"},
    {atomicNumber:65,symbol:"Tb",name:"Terbium",cpkHexColor:"30FFC7",groupBlock:"lanthanoid"},
    {atomicNumber:66,symbol:"Dy",name:"Dysprosium",cpkHexColor:"1FFFC7",groupBlock:"lanthanoid"},
    {atomicNumber:67,symbol:"Ho",name:"Holmium",cpkHexColor:"00FF9C",groupBlock:"lanthanoid"},
    {atomicNumber:68,symbol:"Er",name:"Erbium",cpkHexColor:"00D452",groupBlock:"lanthanoid"},
    {atomicNumber:69,symbol:"Tm",name:"Thulium",cpkHexColor:"00D452",groupBlock:"lanthanoid"},
    {atomicNumber:70,symbol:"Yb",name:"Ytterbium",cpkHexColor:"00BF38",groupBlock:"lanthanoid"},
    {atomicNumber:71,symbol:"Lu",name:"Lutetium",cpkHexColor:"00AB24",groupBlock:"lanthanoid"},
    {atomicNumber:72,symbol:"Hf",name:"Hafnium",cpkHexColor:"4DC2FF",groupBlock:"transition metal"},
    {atomicNumber:73,symbol:"Ta",name:"Tantalum",cpkHexColor:"4DA6FF",groupBlock:"transition metal"},
    {atomicNumber:74,symbol:"W",name:"Tungsten",cpkHexColor:"2194D6",groupBlock:"transition metal"},
    {atomicNumber:75,symbol:"Re",name:"Rhenium",cpkHexColor:"267DAB",groupBlock:"transition metal"},
    {atomicNumber:76,symbol:"Os",name:"Osmium",cpkHexColor:"266696",groupBlock:"transition metal"},
    {atomicNumber:77,symbol:"Ir",name:"Iridium",cpkHexColor:"175487",groupBlock:"transition metal"},
    {atomicNumber:78,symbol:"Pt",name:"Platinum",cpkHexColor:"D0D0E0",groupBlock:"transition metal"},
    {atomicNumber:79,symbol:"Au",name:"Gold",cpkHexColor:"FFD123",groupBlock:"transition metal"},
    {atomicNumber:80,symbol:"Hg",name:"Mercury",cpkHexColor:"B8B8D0",groupBlock:"transition metal"},
    {atomicNumber:81,symbol:"Tl",name:"Thallium",cpkHexColor:"A6544D",groupBlock:"metal"},
    {atomicNumber:82,symbol:"Pb",name:"Lead",cpkHexColor:"575961",groupBlock:"metal"},
    {atomicNumber:83,symbol:"Bi",name:"Bismuth",cpkHexColor:"9E4FB5",groupBlock:"metal"},
    {atomicNumber:84,symbol:"Po",name:"Polonium",cpkHexColor:"AB5C00",groupBlock:"metalloid"},
    {atomicNumber:85,symbol:"At",name:"Astatine",cpkHexColor:"754F45",groupBlock:"halogen"},
    {atomicNumber:86,symbol:"Rn",name:"Radon",cpkHexColor:"428296",groupBlock:"noble gas"},
    {atomicNumber:87,symbol:"Fr",name:"Francium",cpkHexColor:"420066",groupBlock:"alkali metal"},
    {atomicNumber:88,symbol:"Ra",name:"Radium",cpkHexColor:"007D00",groupBlock:"alkaline earth metal"},
    {atomicNumber:89,symbol:"Ac",name:"Actinium",cpkHexColor:"70ABFA",groupBlock:"actinoid"},
    {atomicNumber:90,symbol:"Th",name:"Thorium",cpkHexColor:"00BAFF",groupBlock:"actinoid"},
    {atomicNumber:91,symbol:"Pa",name:"Protactinium",cpkHexColor:"00A1FF",groupBlock:"actinoid"},
    {atomicNumber:92,symbol:"U",name:"Uranium",cpkHexColor:"008FFF",groupBlock:"actinoid"},
    {atomicNumber:93,symbol:"Np",name:"Neptunium",cpkHexColor:"0080FF",groupBlock:"actinoid"},
    {atomicNumber:94,symbol:"Pu",name:"Plutonium",cpkHexColor:"006BFF",groupBlock:"actinoid"},
    {atomicNumber:95,symbol:"Am",name:"Americium",cpkHexColor:"545CF2",groupBlock:"actinoid"},
    {atomicNumber:96,symbol:"Cm",name:"Curium",cpkHexColor:"785CE3",groupBlock:"actinoid"},
    {atomicNumber:97,symbol:"Bk",name:"Berkelium",cpkHexColor:"8A4FE3",groupBlock:"actinoid"},
    {atomicNumber:98,symbol:"Cf",name:"Californium",cpkHexColor:"A136D4",groupBlock:"actinoid"},
    {atomicNumber:99,symbol:"Es",name:"Einsteinium",cpkHexColor:"B31FD4",groupBlock:"actinoid"},
    {atomicNumber:100,symbol:"Fm",name:"Fermium",cpkHexColor:"B31FBA",groupBlock:"actinoid"},
    {atomicNumber:101,symbol:"Md",name:"Mendelevium",cpkHexColor:"B30DA6",groupBlock:"actinoid"},
    {atomicNumber:102,symbol:"No",name:"Nobelium",cpkHexColor:"BD0D87",groupBlock:"actinoid"},
    {atomicNumber:103,symbol:"Lr",name:"Lawrencium",cpkHexColor:"C70066",groupBlock:"transition metal"},
    {atomicNumber:104,symbol:"Rf",name:"Rutherfordium",cpkHexColor:"CC0059",groupBlock:"transition metal"},
    {atomicNumber:105,symbol:"Db",name:"Dubnium",cpkHexColor:"D1004F",groupBlock:"transition metal"},
    {atomicNumber:106,symbol:"Sg",name:"Seaborgium",cpkHexColor:"D90045",groupBlock:"transition metal"},
    {atomicNumber:107,symbol:"Bh",name:"Bohrium",cpkHexColor:"E00038",groupBlock:"transition metal"},
    {atomicNumber:108,symbol:"Hs",name:"Hassium",cpkHexColor:"E6002E",groupBlock:"transition metal"},
    {atomicNumber:109,symbol:"Mt",name:"Meitnerium",cpkHexColor:"EB0026",groupBlock:"transition metal"},
    {atomicNumber:110,symbol:"Ds",name:"Darmstadtium",cpkHexColor:"",groupBlock:"transition metal"},
    {atomicNumber:111,symbol:"Rg",name:"Roentgenium",cpkHexColor:"",groupBlock:"transition metal"},
    {atomicNumber:112,symbol:"Cn",name:"Copernicium",cpkHexColor:"",groupBlock:"transition metal"},
    {atomicNumber:113,symbol:"Nh",name:"Nihonium",cpkHexColor:"",groupBlock:"post-transition metal"},
    {atomicNumber:114,symbol:"Fl",name:"Flerovium",cpkHexColor:"",groupBlock:"post-transition metal"},
    {atomicNumber:115,symbol:"Mc",name:"Moscovium",cpkHexColor:"",groupBlock:"post-transition metal"},
    {atomicNumber:116,symbol:"Lv",name:"Livermorium",cpkHexColor:"",groupBlock:"post-transition metal"},
    {atomicNumber:117,symbol:"Ts",name:"Tennessine",cpkHexColor:"",groupBlock:"post-transition metal"},
    {atomicNumber:118,symbol:"Og",name:"Oganesson",cpkHexColor:"",groupBlock:"noble gas"}
  ];