// elements.js — Full 118 elements with extra data (ready for future upgrades!)
const elements = [
    {atomicNumber:1,symbol:"H",name:"Hidrogen",cpkHexColor:"FFFFFF",groupBlock:"nonmetal"},
    {atomicNumber:2,symbol:"He",name:"Heli",cpkHexColor:"D9FFFF",groupBlock:"noble gas"},
    {atomicNumber:3,symbol:"Li",name:"Liti",cpkHexColor:"CC80FF",groupBlock:"alkali metal"},
    {atomicNumber:4,symbol:"Be",name:"Beril·li",cpkHexColor:"C2FF00",groupBlock:"alkaline earth metal"},
    {atomicNumber:5,symbol:"B",name:"Bor",cpkHexColor:"FFB5B5",groupBlock:"metalloid"},
    {atomicNumber:6,symbol:"C",name:"Carboni",cpkHexColor:"909090",groupBlock:"nonmetal"},
    {atomicNumber:7,symbol:"N",name:"Nitrogen",cpkHexColor:"3050F8",groupBlock:"nonmetal"},
    {atomicNumber:8,symbol:"O",name:"Oxigen",cpkHexColor:"FF0D0D",groupBlock:"nonmetal"},
    {atomicNumber:9,symbol:"F",name:"Flúor",cpkHexColor:"90E050",groupBlock:"halogen"},
    {atomicNumber:10,symbol:"Ne",name:"Neó",cpkHexColor:"B3E3F5",groupBlock:"noble gas"},
    {atomicNumber:11,symbol:"Na",name:"Sodi",cpkHexColor:"AB5CF2",groupBlock:"alkali metal"},
    {atomicNumber:12,symbol:"Mg",name:"Magnesi",cpkHexColor:"8AFF00",groupBlock:"alkaline earth metal"},
    {atomicNumber:13,symbol:"Al",name:"Alumini",cpkHexColor:"BFA6A6",groupBlock:"metal"},
    {atomicNumber:14,symbol:"Si",name:"Silici",cpkHexColor:"F0C8A0",groupBlock:"metalloid"},
    {atomicNumber:15,symbol:"P",name:"Fósfor",cpkHexColor:"FF8000",groupBlock:"nonmetal"},
    {atomicNumber:16,symbol:"S",name:"Sofre",cpkHexColor:"FFFF30",groupBlock:"nonmetal"},
    {atomicNumber:17,symbol:"Cl",name:"Clor",cpkHexColor:"1FF01F",groupBlock:"halogen"},
    {atomicNumber:18,symbol:"Ar",name:"Argó",cpkHexColor:"80D1E3",groupBlock:"noble gas"},
    {atomicNumber:19,symbol:"K",name:"Potassi",cpkHexColor:"8F40D4",groupBlock:"alkali metal"},
    {atomicNumber:20,symbol:"Ca",name:"Calci",cpkHexColor:"3DFF00",groupBlock:"alkaline earth metal"},
    {atomicNumber:21,symbol:"Sc",name:"Scandi",cpkHexColor:"E6E6E6",groupBlock:"transition metal"},
    {atomicNumber:22,symbol:"Ti",name:"Titani",cpkHexColor:"BFC2C7",groupBlock:"transition metal"},
    {atomicNumber:23,symbol:"V",name:"Vanadi",cpkHexColor:"A6A6AB",groupBlock:"transition metal"},
    {atomicNumber:24,symbol:"Cr",name:"Crom",cpkHexColor:"8A99C7",groupBlock:"transition metal"},
    {atomicNumber:25,symbol:"Mn",name:"Manganès",cpkHexColor:"9C7AC7",groupBlock:"transition metal"},
    {atomicNumber:26,symbol:"Fe",name:"Ferro",cpkHexColor:"E06633",groupBlock:"transition metal"},
    {atomicNumber:27,symbol:"Co",name:"Cobalt",cpkHexColor:"F090A0",groupBlock:"transition metal"},
    {atomicNumber:28,symbol:"Ni",name:"Niquel",cpkHexColor:"50D050",groupBlock:"transition metal"},
    {atomicNumber:29,symbol:"Cu",name:"Coure",cpkHexColor:"C88033",groupBlock:"transition metal"},
    {atomicNumber:30,symbol:"Zn",name:"Zinc",cpkHexColor:"7D80B0",groupBlock:"transition metal"},
    {atomicNumber:31,symbol:"Ga",name:"Gal·li",cpkHexColor:"C28F8F",groupBlock:"metal"},
    {atomicNumber:32,symbol:"Ge",name:"Germani",cpkHexColor:"668F8F",groupBlock:"metalloid"},
    {atomicNumber:33,symbol:"As",name:"Arsènic",cpkHexColor:"BD80E3",groupBlock:"metalloid"},
    {atomicNumber:34,symbol:"Se",name:"Seleni",cpkHexColor:"FFA100",groupBlock:"nonmetal"},
    {atomicNumber:35,symbol:"Br",name:"Brom",cpkHexColor:"A62929",groupBlock:"halogen"},
    {atomicNumber:36,symbol:"Kr",name:"Kriptó",cpkHexColor:"5CB8D1",groupBlock:"noble gas"},
    {atomicNumber:37,symbol:"Rb",name:"Rubidi",cpkHexColor:"702EB0",groupBlock:"alkali metal"},
    {atomicNumber:38,symbol:"Sr",name:"Stronci",cpkHexColor:"00FF00",groupBlock:"alkaline earth metal"},
    {atomicNumber:39,symbol:"Y",name:"Itri",cpkHexColor:"94FFFF",groupBlock:"transition metal"},
    {atomicNumber:40,symbol:"Zr",name:"Zirconi",cpkHexColor:"94E0E0",groupBlock:"transition metal"},
    {atomicNumber:41,symbol:"Nb",name:"Niobi",cpkHexColor:"73C2C9",groupBlock:"transition metal"},
    {atomicNumber:42,symbol:"Mo",name:"Molibdè",cpkHexColor:"54B5B5",groupBlock:"transition metal"},
    {atomicNumber:43,symbol:"Tc",name:"Tecneci",cpkHexColor:"3B9E9E",groupBlock:"transition metal"},
    {atomicNumber:44,symbol:"Ru",name:"Ruteni",cpkHexColor:"248F8F",groupBlock:"transition metal"},
    {atomicNumber:45,symbol:"Rh",name:"Rodi",cpkHexColor:"0A7D8C",groupBlock:"transition metal"},
    {atomicNumber:46,symbol:"Pd",name:"Pal·ladi",cpkHexColor:"006985",groupBlock:"transition metal"},
    {atomicNumber:47,symbol:"Ag",name:"Plata Argent",cpkHexColor:"C0C0C0",groupBlock:"transition metal"},
    {atomicNumber:48,symbol:"Cd",name:"Cadmi",cpkHexColor:"FFD98F",groupBlock:"transition metal"},
    {atomicNumber:49,symbol:"In",name:"Indi",cpkHexColor:"A67573",groupBlock:"metal"},
    {atomicNumber:50,symbol:"Sn",name:"Estany",cpkHexColor:"668080",groupBlock:"metal"},
    {atomicNumber:51,symbol:"Sb",name:"Antimoni",cpkHexColor:"9E63B5",groupBlock:"metalloid"},
    {atomicNumber:52,symbol:"Te",name:"Tel·luri",cpkHexColor:"D47A00",groupBlock:"metalloid"},
    {atomicNumber:53,symbol:"I",name:"Iode",cpkHexColor:"940094",groupBlock:"halogen"},
    {atomicNumber:54,symbol:"Xe",name:"Xenó",cpkHexColor:"429EB0",groupBlock: "noble gas"},
    {atomicNumber:55,symbol:"Cs",name:"Cesi",cpkHexColor:"57178F",groupBlock:"alkali metal"},
    {atomicNumber:56,symbol:"Ba",name:"Bari",cpkHexColor:"00C900",groupBlock:"alkaline earth metal"},
    {atomicNumber:57,symbol:"La",name:"Lantani",cpkHexColor:"70D4FF",groupBlock:"lanthanoid"},
    {atomicNumber:58,symbol:"Ce",name:"Ceri",cpkHexColor:"FFFFC7",groupBlock:"lanthanoid"},
    {atomicNumber:59,symbol:"Pr",name:"Praseodimi",cpkHexColor:"D9FFC7",groupBlock:"lanthanoid"},
    {atomicNumber:60,symbol:"Nd",name:"Neodimi",cpkHexColor:"C7FFC7",groupBlock:"lanthanoid"},
    {atomicNumber:61,symbol:"Pm",name:"Prometi",cpkHexColor:"A3FFC7",groupBlock:"lanthanoid"},
    {atomicNumber:62,symbol:"Sm",name:"Samari",cpkHexColor:"8FFFC7",groupBlock:"lanthanoid"},
    {atomicNumber:63,symbol:"Eu",name:"Europi",cpkHexColor:"61FFC7",groupBlock:"lanthanoid"},
    {atomicNumber:64,symbol:"Gd",name:"Gadolini",cpkHexColor:"45FFC7",groupBlock:"lanthanoid"},
    {atomicNumber:65,symbol:"Tb",name:"Terbi",cpkHexColor:"30FFC7",groupBlock:"lanthanoid"},
    {atomicNumber:66,symbol:"Dy",name:"Disprosi",cpkHexColor:"1FFFC7",groupBlock:"lanthanoid"},
    {atomicNumber:67,symbol:"Ho",name:"Holmi",cpkHexColor:"00FF9C",groupBlock:"lanthanoid"},
    {atomicNumber:68,symbol:"Er",name:"Erbi",cpkHexColor:"00D452",groupBlock:"lanthanoid"},
    {atomicNumber:69,symbol:"Tm",name:"Tuli",cpkHexColor:"00D452",groupBlock:"lanthanoid"},
    {atomicNumber:70,symbol:"Yb",name:"Iterbi",cpkHexColor:"00BF38",groupBlock:"lanthanoid"},
    {atomicNumber:71,symbol:"Lu",name:"Luteci",cpkHexColor:"00AB24",groupBlock:"lanthanoid"},
    {atomicNumber:72,symbol:"Hf",name:"Hafni",cpkHexColor:"4DC2FF",groupBlock:"transition metal"},
    {atomicNumber:73,symbol:"Ta",name:"Tàntal",cpkHexColor:"4DA6FF",groupBlock:"transition metal"},
    {atomicNumber:74,symbol:"W",name:"Tungstè",cpkHexColor:"2194D6",groupBlock:"transition metal"},
    {atomicNumber:75,symbol:"Re",name:"Reni",cpkHexColor:"267DAB",groupBlock:"transition metal"},
    {atomicNumber:76,symbol:"Os",name:"Osmi",cpkHexColor:"266696",groupBlock:"transition metal"},
    {atomicNumber:77,symbol:"Ir",name:"Iridi",cpkHexColor:"175487",groupBlock:"transition metal"},
    {atomicNumber:78,symbol:"Pt",name:"Platí",cpkHexColor:"D0D0E0",groupBlock:"transition metal"},
    {atomicNumber:79,symbol:"Au",name:"Or",cpkHexColor:"FFD123",groupBlock:"transition metal"},
    {atomicNumber:80,symbol:"Hg",name:"Mercuri",cpkHexColor:"B8B8D0",groupBlock:"transition metal"},
    {atomicNumber:81,symbol:"Tl",name:"Tal·li",cpkHexColor:"A6544D",groupBlock:"metal"},
    {atomicNumber:82,symbol:"Pb",name:"Plom",cpkHexColor:"575961",groupBlock:"metal"},
    {atomicNumber:83,symbol:"Bi",name:"Bismut",cpkHexColor:"9E4FB5",groupBlock:"metal"},
    {atomicNumber:84,symbol:"Po",name:"Poloni",cpkHexColor:"AB5C00",groupBlock:"metalloid"},
    {atomicNumber:85,symbol:"At",name:"Àstat",cpkHexColor:"754F45",groupBlock:"nonmetal"},
    {atomicNumber:86,symbol:"Rn",name:"Radó",cpkHexColor:"428296",groupBlock:"noble gas"},
    {atomicNumber:87,symbol:"Fr",name:"Franci",cpkHexColor:"420066",groupBlock:"alkali metal"},
    {atomicNumber:88,symbol:"Ra",name:"Radi",cpkHexColor:"007D00",groupBlock:"alkaline earth metal"},
    {atomicNumber:89,symbol:"Ac",name:"Actini",cpkHexColor:"70ABFA",groupBlock:"actinoid"},
    {atomicNumber:90,symbol:"Th",name:"Tori",cpkHexColor:"00BAFF",groupBlock:"actinoid"},
    {atomicNumber:91,symbol:"Pa",name:"Protoactini",cpkHexColor:"00A1FF",groupBlock:"actinoid"},
    {atomicNumber:92,symbol:"U",name:"Urani",cpkHexColor:"008FFF",groupBlock:"actinoid"},
    {atomicNumber:93,symbol:"Np",name:"Neptuni",cpkHexColor:"0080FF",groupBlock:"actinoid"},
    {atomicNumber:94,symbol:"Pu",name:"Plutoni",cpkHexColor:"006BFF",groupBlock:"actinoid"},
    {atomicNumber:95,symbol:"Am",name:"Americi",cpkHexColor:"545CF2",groupBlock:"actinoid"},
    {atomicNumber:96,symbol:"Cm",name:"Curi",cpkHexColor:"785CE3",groupBlock:"actinoid"},
    {atomicNumber:97,symbol:"Bk",name:"Berkeli",cpkHexColor:"8A4FE3",groupBlock:"actinoid"},
    {atomicNumber:98,symbol:"Cf",name:"Californi",cpkHexColor:"A136D4",groupBlock:"actinoid"},
    {atomicNumber:99,symbol:"Es",name:"Einsteini",cpkHexColor:"B31FD4",groupBlock:"actinoid"},
    {atomicNumber:100,symbol:"Fm",name:"Fermi",cpkHexColor:"B31FBA",groupBlock:"actinoid"},
    {atomicNumber:101,symbol:"Md",name:"Mendelevi",cpkHexColor:"B30DA6",groupBlock:"actinoid"},
    {atomicNumber:102,symbol:"No",name:"Nobeli",cpkHexColor:"BD0D87",groupBlock:"actinoid"},
    {atomicNumber:103,symbol:"Lr",name:"Lawrenci",cpkHexColor:"C70066",groupBlock:"transition metal"},
    {atomicNumber:104,symbol:"Rf",name:"Rutherfordi",cpkHexColor:"CC0059",groupBlock:"transition metal"},
    {atomicNumber:105,symbol:"Db",name:"Dubni",cpkHexColor:"D1004F",groupBlock:"transition metal"},
    {atomicNumber:106,symbol:"Sg",name:"Seaborgi",cpkHexColor:"D90045",groupBlock:"transition metal"},
    {atomicNumber:107,symbol:"Bh",name:"Bohri",cpkHexColor:"E00038",groupBlock:"transition metal"},
    {atomicNumber:108,symbol:"Hs",name:"Hassi",cpkHexColor:"E6002E",groupBlock:"transition metal"},
    {atomicNumber:109,symbol:"Mt",name:"Meitneri",cpkHexColor:"EB0026",groupBlock:"transition metal"},
    {atomicNumber:110,symbol:"Ds",name:"Darmstadti",cpkHexColor:"",groupBlock:"transition metal"},
    {atomicNumber:111,symbol:"Rg",name:"Roentgeni",cpkHexColor:"",groupBlock:"transition metal"},
    {atomicNumber:112,symbol:"Cn",name:"Copernici",cpkHexColor:"",groupBlock:"transition metal"},
    {atomicNumber:113,symbol:"Nh",name:"Nihoni",cpkHexColor:"",groupBlock:"post-transition metal"},
    {atomicNumber:114,symbol:"Fl",name:"Flerovi",cpkHexColor:"",groupBlock:"post-transition metal"},
    {atomicNumber:115,symbol:"Mc",name:"Moscovi",cpkHexColor:"",groupBlock:"post-transition metal"},
    {atomicNumber:116,symbol:"Lv",name:"Livermori",cpkHexColor:"",groupBlock:"post-transition metal"},
    {atomicNumber:117,symbol:"Ts",name:"Tennes",cpkHexColor:"",groupBlock:"nonmetal"},
    {atomicNumber:118,symbol:"Og",name:"Oganessó",cpkHexColor:"",groupBlock:"noble gas"}
  ];

// Afegim category basada en groupBlock
elements.forEach(e => {
  let cat;
  if (e.groupBlock.includes("metal") && !e.groupBlock.includes("alkali") && !e.groupBlock.includes("alkaline")) cat="metal";
  else if (e.groupBlock.includes("alkali") || e.groupBlock.includes("alkaline")) cat="metal";
  else if (e.groupBlock.includes("metalloid")) cat="semi-metal";
  else if (e.groupBlock.includes("nonmetal") || e.groupBlock.includes("halogen")) cat="nonmetal";
  else if (e.groupBlock.includes("noble gas")) cat="noble-gas";
  else if (e.groupBlock.includes("lanthanoid") || e.groupBlock.includes("actinoid")) cat="metal";
  else cat="metal";
  e.category = cat;
});

